on:
  workflow_dispatch: ~
  push:
    branches:
      - master

jobs:
  build-source:
    runs-on: macOS-latest

    name: "Build source"

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@master

      - name: Install dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_github("reside-ic/repobuilder@prototype")
        shell: Rscript {0}

      - name: Build packages
        shell: Rscript {0}
        run: |
          repobuilder:::gha_build()

      - name: Upload package
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: sources
          path: gha

  build-packages:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: macOS-latest,   r: 'oldrel'}
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: 'oldrel'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: Install dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_github("reside-ic/repobuilder@prototype")
        shell: Rscript {0}

      - uses: actions/download-artifact@v2
        with:
          name: sources

      - name: Build packages
        shell: Rscript {0}
        run: |
          repobuilder:::gha_binaries()

      - name: Upload package
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: binary-${{ runner.os }}-r${{ matrix.config.r }}
          path: work/bin
