on:
  workflow_dispatch: ~
  push:
    branches:
      - master

jobs:
  build-source:
    runs-on: macOS-latest

    name: "Build source"

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@master

      - name: Install dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_github("reside-ic/repobuilder@prototype")
        shell: Rscript {0}

      - name: Build packages
        shell: Rscript {0}
        run: |
          repobuilder:::gha_source()

      - name: Upload package
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: sources
          path: gha

  build-packages:
    needs: build-source

    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: macOS-latest,   r: 'oldrel'}
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: 'oldrel'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: sources
          path: gha

      - name: Check if action needed
        shell: bash
        run: |
          echo "::set-env name=REPOBUILDER_BUILD::$(cat gha/src/build)"

      - uses: r-lib/actions/setup-r@master
        if: env.REPOBUILDER_BUILD == 'TRUE'
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: Install dependencies
        if: env.REPOBUILDER_BUILD == 'TRUE'
        run: |
          install.packages(c("remotes"))
          remotes::install_github("reside-ic/repobuilder@prototype")
        shell: Rscript {0}

      - name: Build packages
        if: env.REPOBUILDER_BUILD == 'TRUE'
        shell: Rscript {0}
        run: |
          repobuilder:::gha_binaries()

      - name: Upload package
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: binaries-${{ matrix.config.os }}-${{ matrix.config.r }}
          path: gha/packages

  build-site:
    needs: build-packages
    runs-on: macOS-latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v2
        with:
          path: gha

      - name: Check if action needed
        shell: bash
        run: |
          echo "::set-env name=REPOBUILDER_BUILD::$(cat gha/sources/src/build)"

      - uses: r-lib/actions/setup-r@master
        if: env.REPOBUILDER_BUILD == 'TRUE'
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: Install dependencies
        if: env.REPOBUILDER_BUILD == 'TRUE'
        run: |
          install.packages(c("remotes"))
          remotes::install_github("reside-ic/repobuilder@prototype")
        shell: Rscript {0}

      - name: Deploy site
        if: env.REPOBUILDER_BUILD == 'TRUE'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'repobuilder:::gha_site()'
          git push origin gh-pages
