on:
  workflow_dispatch: ~
  push:
    branches:
      - master

jobs:
  build-source:
    runs-on: macOS-latest

    name: "Build source"

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build packages
        shell: bash
        run: |
          mkdir -p gha/source
          touch gha/source/dde_1.0.2.tar.gz
          touch gha/source/ring_1.0.1.tar.gz
          touch gha/source/packages.yml

      - name: Upload package
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: sources
          path: gha

  build-packages:
    needs: build-source

    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          # - {os: macOS-latest,   r: 'oldrel'}
          - {os: windows-latest, r: 'release'}
          # - {os: windows-latest, r: 'oldrel'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: sources
          path: gha

      - name: Build packages
        shell: bash
        run: |
          ls -R gha
          mkdir -p gha/bin/${{ matrix.config.os }}/${{ matrix.config.r }}
          touch gha/bin/${{ matrix.config.os }}/${{ matrix.config.r }}/ring.zip
          touch gha/bin/${{ matrix.config.os }}/${{ matrix.config.r }}/dde.zip
          touch gha/bin/${{ matrix.config.os }}/${{ matrix.config.r }}/packages.yml

      - name: Upload package
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: binaries-${{ matrix.config.os }}-${{ matrix.config.r }}
          path: gha/bin

  build-site:
    needs: build-packages
    runs-on: macOS-latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}


    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v2
        with:
          path: gha

      - name: Build site
        shell: bash
        run: |
          ls -R gha
